Clear vulns via NPM updates
SalesforceFoundation/PMM pull request #275
Opened 2020-08-26 17:50 UTC by davidmreed

This PR clears security warnings in obsolete dependencies by updating to the latest lwc-jest package.

Note: this PR may require you to update your Node version.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Place holder data is incorporated (Refer to [Case Management Sample Data document](https://quip.com/cbFcAPJF8t0z))
- [ ] Base axe-core JEST test included for any new LWC (No critical violations)
- [ ] CRUD/FLS is enforced in Apex
- [ ] Update & Test permission sets to account for new features and CRUD/FLS
- [ ] All modified classes are unit tested (Apex) at 100% coverage
- [ ] UX approval or UX not necessary
- [ ] PR contains draft release notes
- [ ] Attach work item to the pull request with [Lurch](https://salesforce.quip.com/50ZRA5LEWVzH) `**Lurch:attach W-000000` or `**Lurch:add`
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] QE story level testing completed

2020-08-31 19:19 UTC, davidmreed commented
Note: if this API version update is problematic, I have another strategy we can try.

2020-09-08 22:05 UTC, jjbennett approved these changes
Looks good!

2020-09-08 22:14 UTC, jjbennett requested changes
Take that back, we are investigating an issue with the jest tests erroring.

2020-09-08 22:30 UTC, jjbennett approved these changes
Note: To update locally first remove your node_modules before running yarn. "delete the node_modules directory (e.g. rm -rf node_modules) and call yarn install again."

2020-09-08 22:37 UTC, merged