Feature/winter 21  add service participants
SalesforceFoundation/PMM pull request #287
Opened 2020-09-11 22:13 UTC by bmuniswamy

# Critical Changes

# Changes
  This is participant selection screen. This screen will display all the contacts associated with the program engagements for the given service. The users can select the participants that will be part of the sessions being created.
# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
~~- [ ] Place holder data is incorporated (Refer to [Case Management Sample Data document](https://quip.com/cbFcAPJF8t0z))~~
~~- [ ] Base axe-core JEST test included for any new LWC (No critical violations)~~
~~- [ ] CRUD/FLS is enforced in Apex~~
~~- [ ] Update & Test permission sets to account for new features and CRUD/FLS~~
- [x] All modified classes are unit tested (Apex) at 100% coverage
- [x] UX approval or UX not necessary
- [x] PR contains draft release notes
- [x] Attach work item to the pull request with [Lurch](https://salesforce.quip.com/50ZRA5LEWVzH) `**Lurch:attach W-000000` or `**Lurch:add`
- [ ] All **acceptance criteria** have been met
    - [x] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] QE story level testing completed

2020-09-11 22:14 UTC, bmuniswamy commented
[W-7981519](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008XFKQIA4/view)

2020-09-11 22:15 UTC, bmuniswamy commented
@AndersonTarren , I had to add 3 labels for this work item. Sorry I missed it last week.

2020-09-14 17:42 UTC, bethbrains commented on force-app/main/default/classes/SelectParticipantService.cls
> +    public InitialDataAndSetup getInitialDataSetup(Id serviceId) {
`getSelectParticipantModel`

2020-09-14 17:43 UTC, bethbrains commented on force-app/main/default/classes/SelectParticipantService.cls
> +    public class InitialDataAndSetup {
`SelectParticipantModel`

2020-09-14 17:43 UTC, bethbrains commented on force-app/main/default/classes/SelectParticipantService.cls
> +        public InitialDataAndSetup() {
```suggestion
        public SelectParticipantModel() {
```

2020-09-14 17:44 UTC, bethbrains commented on force-app/main/default/classes/SelectParticipantController.cls
> +    public static selectParticipantService.InitialDataAndSetup getInitialDataSetup(
capital S on `SelectParticipantService.SelectParticipantModel`

2020-09-14 17:44 UTC, bethbrains commented on force-app/main/default/classes/SelectParticipantController.cls
> +    public static selectParticipantService.InitialDataAndSetup getInitialDataSetup(
`getSelectParticipantModel`

2020-09-14 17:45 UTC, bethbrains commented on force-app/main/default/classes/SelectParticipantController_TEST.cls
> +@isTest
```suggestion
@IsTest
```

2020-09-14 17:46 UTC, bethbrains commented on force-app/main/default/classes/SelectParticipantController_TEST.cls
> +        serviceStub.withReturnValue('getInitialDataSetup', Id.class, expected);
Use var for method name

2020-09-14 17:48 UTC, bethbrains commented on force-app/main/default/classes/SelectParticipantSelector.cls
> +public with sharing class SelectParticipantSelector {
```suggestion
public with sharing class ServiceParticipantSelector {
```

2020-09-14 17:51 UTC, bethbrains commented on force-app/main/default/classes/SelectParticipantService.cls
> +    public Map<String, String> getObjectData() {
getLabels

2020-09-14 19:03 UTC, bethbrains requested changes
GREAT work. Great mob review.

2020-09-14 19:03 UTC, bethbrains commented on force-app/main/default/lwc/selectedParticipantList/selectedParticipantList.js
> +            this.selectedParticipants && this.selectedParticipants.length === 0;
```suggestion
    handleRemove(event) {
```
The parent handles the actual removal from the array and passes back down the updated array.

2020-09-15 20:50 UTC, jjbennett reviewed
A couple nit picky things on the apex side, let's hop on a call for the js side of things.

2020-09-16 16:00 UTC, jjbennett approved these changes
A couple comments but no show stoppers, I know you still have the css to tweak on the right table but overall I think this is an amazing first pass. Thanks again for consolidating the code, I think it streamlines the communication!

2020-09-16 16:08 UTC, bmuniswamy commented
enqueLoadrecords calls the applyFliter method that will be used when a user types in the input text search.

2020-09-16 16:11 UTC, bmuniswamy commented
@jjbennett , I was setting the result to undefined if there is an error. I learnt that from the superbadge and if that is not the right approach please let me know

2020-09-16 16:14 UTC, jjbennett commented on force-app/main/default/lwc/participantSelector/participantSelector.js
> +            result = undefined;
I believe the idea is to set the variables that held the results to undefined but not the result itself.

2020-09-17 20:18 UTC, merged