Group Services: create Sessions (Screen 2)
SalesforceFoundation/PMM pull request #298
Opened 2020-09-21 23:14 UTC by bethbrains

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Place holder data is incorporated (Refer to [Case Management Sample Data document](https://quip.com/cbFcAPJF8t0z))
- [ ] Base axe-core JEST test included for any new LWC (No critical violations)
- [ ] CRUD/FLS is enforced in Apex
- [ ] Update & Test permission sets to account for new features and CRUD/FLS
- [ ] All modified classes are unit tested (Apex) at 100% coverage
- [ ] UX approval or UX not necessary
- [ ] PR contains draft release notes
- [ ] Attach work item to the pull request with [Lurch](https://salesforce.quip.com/50ZRA5LEWVzH) `**Lurch:attach W-000000` or `**Lurch:add`
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] QE story level testing completed

2020-09-22 16:47 UTC, bmuniswamy requested changes
@bethbrains , A couple of things that needs to be looked at. Also I noticed that if we do not go all the way through using the wizard and close the wizard and go back to the service and try to create a new schedule , for some reason it looks like the context to the service is lost and the service name on first screen is blank.

Also what is the DS_Store file used for. I have not seen that before

2020-09-22 16:47 UTC, bmuniswamy commented on force-app/main/default/classes/ServiceScheduleService_TEST.cls
> +        System.assertEquals(expected, actual);
@bethbrains , Can we add a message that the users will see if this assert fails.

2020-09-22 16:47 UTC, bmuniswamy commented on force-app/main/default/classes/ServiceScheduleService_TEST.cls
> +        System.debug(JSON.serialize(expected));
```suggestion

```
Can we remove the system.debug statements here

2020-09-22 16:47 UTC, bmuniswamy commented on force-app/main/default/classes/ServiceScheduleService_TEST.cls
> +        System.assertEquals(expected, actual);
@bethbrains , Just to be consistent can we add a message here

2020-09-22 16:47 UTC, bmuniswamy commented on force-app/main/default/lwc/reviewSessions/reviewSessions.js
>          // setting the columns on the datatable
```suggestion

```
We may want to remove this comment or even change the comment

2020-09-22 16:47 UTC, bmuniswamy commented on force-app/main/default/lwc/reviewSessions/reviewSessions.js
> +        this.getSessions();
@bethbrains , One thing I noticed is that the datatable does not show all the sessions after the values are entered on Screen1 and the next button is clicked. So to have the data populated in the datatable we will have to click Next and go to screen 3 and then we have to come back to screen 2 to see the new changes. This happens only when the Service Schedule Ends is set to a date.

2020-09-22 16:47 UTC, bmuniswamy commented on force-app/main/default/lwc/reviewSessions/reviewSessions.js
>                  label: this.sessionStartLabel,
No labels are displayed on the datatable

2020-09-22 21:47 UTC, bethbrains commented on force-app/main/default/classes/ServiceScheduleService.cls
> +            DateTime endDateTime = schedule.FirstSessionEnd__c != null
Thought about it... It would need 4 parameters, if not 5, so it just seemed not worth it. Can iterate later if you feel strongly.

2020-09-23 13:48 UTC, jjbennett commented
It looks like the lightning datatable is using the browser locale and not Salesforce. Not sure if we want to try and deal with this now or later or document it?
![Screen1](https://user-images.githubusercontent.com/450473/94021365-8d32ac80-fd79-11ea-9b14-8d63e3f66b67.png)
![Screen2](https://user-images.githubusercontent.com/450473/94021368-8dcb4300-fd79-11ea-8402-57a778dff1a9.png)
![SalesforceUI](https://user-images.githubusercontent.com/450473/94021370-8e63d980-fd79-11ea-915a-a9257641d605.png)

2020-09-23 13:53 UTC, jjbennett commented on force-app/main/default/classes/ServiceScheduleService.cls
> +            DateTime endDateTime = schedule.FirstSessionEnd__c != null
Sounds good, I think we'd be ok just passing the schedule and the startDateTime to the method, not really necessary to pull out the primary and other service providers but totally cool with iterating later. I also like the idea of just using the default on line 49 vs hardcoding the value.

2020-09-23 13:58 UTC, jjbennett commented on force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
> +    handleStartChange(event) {
This makes it so much more clear in the UI with the defaults, love this addition!

2020-09-23 13:59 UTC, jjbennett commented on force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
> +    handleStartChange(event) {
We might need a little bullet proofing though. I get an error if I click end and then click start...
![EndBeforeStart](https://user-images.githubusercontent.com/450473/94022856-2615f780-fd7b-11ea-855f-1c8266f52a0b.png)

2020-09-23 14:11 UTC, jjbennett commented on force-app/main/default/lwc/reviewSessions/reviewSessions.js
> +                    session[field.apiName] !== event.detail.row[field.apiName],
Running into a couple issues if I intentionally clear out the ending date/time on page 1. When I delete the session everything is filtered out. I also noticed a warning in the console from the formatted date time component about it being provided an invalid date.
![InvalidDate](https://user-images.githubusercontent.com/450473/94024219-c4568d00-fd7c-11ea-8c83-f477389c4462.png)

2020-09-24 22:06 UTC, bmuniswamy approved these changes

2020-09-24 22:16 UTC, bethbrains commented
[W-8043637](https://gus.lightning.force.com/a07B0000008cj0nIAA)
[W-8080261](https://gus.lightning.force.com/a07B0000008InZnIAK)
[W-8056275](https://gus.lightning.force.com/a07B0000008crUjIAI)
[W-8056175](https://gus.lightning.force.com/a07B0000008crPoIAI)
[W-8043613](https://gus.lightning.force.com/a07B0000008cizpIAA)
[W-8043617](https://gus.lightning.force.com/a07B0000008cj04IAA)
[W-8043620](https://gus.lightning.force.com/a07B0000008cj0EIAQ)
whew!

2020-09-25 22:08 UTC, merged