Feature/winter 21  add sessions
SalesforceFoundation/PMM pull request #305
Opened 2020-10-02 16:28 UTC by jjbennett

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Place holder data is incorporated (Refer to [Case Management Sample Data document](https://quip.com/cbFcAPJF8t0z))
- [ ] Base axe-core JEST test included for any new LWC (No critical violations)
- [ ] CRUD/FLS is enforced in Apex
- [ ] Update & Test permission sets to account for new features and CRUD/FLS
- [ ] All modified classes are unit tested (Apex) at 100% coverage
- [ ] UX approval or UX not necessary
- [ ] PR contains draft release notes
- [ ] Attach work item to the pull request with [Lurch](https://salesforce.quip.com/50ZRA5LEWVzH) `**Lurch:attach W-000000` or `**Lurch:add`
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] QE story level testing completed

2020-10-02 16:28 UTC, jjbennett commented
[W-8013901](https://gus.lightning.force.com/a07B0000008IORLIA4)

2020-10-02 21:52 UTC, bethbrains requested changes
Looks great. 1 question.

2020-10-02 21:52 UTC, bethbrains commented on force-app/main/default/classes/ServiceScheduleDomain.cls
> +            session.OtherServiceProvider__c = model.serviceSchedule.OtherServiceProvider__c;
love doing this here. so much cleaner.

2020-10-02 21:52 UTC, bethbrains commented on force-app/main/default/lwc/modal/modal.js
> +            (this.isNested ? " nested-modal" : "")
clever!

2020-10-02 21:52 UTC, bethbrains commented on force-app/main/default/lwc/reviewSessions/reviewSessions.js
> +        this.objectName = this._serviceScheduleModel.labels.serviceSession.objectApiName;
this was being used to display "x sessions" so we probably need another property for this.pluralobjectlabel or something?

2020-10-02 21:56 UTC, bethbrains approved these changes
Looks great.

2020-10-06 18:55 UTC, AndersonTarren approved these changes
Code Owner Approval

2020-10-06 18:55 UTC, merged