Feature/attendance  recent sessions on home page  ui fixes
SalesforceFoundation/PMM pull request #349
Opened 2020-11-12 20:30 UTC by bmuniswamy

# Critical Changes

# Changes
    Moved the individual card to sessionCard component. Added status condition to the ServiceSessionSelector class so we only show Pending and Complete status. Added NavigationMixin so when the sessionName is clicked it takes the user to the serviceSession record View page where the attendance component will reside.
# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Place holder data is incorporated (Refer to [Case Management Sample Data document](https://quip.com/cbFcAPJF8t0z))
- [ ] Base axe-core JEST test included for any new LWC (No critical violations)
- [ ] CRUD/FLS is enforced in Apex
- [ ] Permission sets & field sets are updated to account for CRUD/FLS/TABS for new object metadata
- [ ] All modified classes are unit tested (Apex) at 100% coverage
- [ ] UX approval or UX not necessary
- [ ] PR contains draft release notes
- [ ] Attach work item to the pull request with [Lurch](https://salesforce.quip.com/50ZRA5LEWVzH) `**Lurch:attach W-000000` or `**Lurch:add`
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] QE story level testing completed

2020-11-12 23:56 UTC, bmuniswamy commented
[W-8091293](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008IsNZIA0/view)

2020-11-16 20:02 UTC, bethbrains requested changes
A few small changes requested. Great work!

2020-11-16 22:40 UTC, bmuniswamy commented on force-app/main/default/lwc/recentSessions/recentSessions.html
> +                <span class="slds-card__header-title">{labels.recentSessions}</span>
Had to remove the css class from the h1 tag. We will need the span here

2020-11-16 22:41 UTC, bmuniswamy commented on force-app/main/default/lwc/recentSessions/recentSessions.js
> +                if (key === THIS_WEEK) {
I have declared this as a constant on line 20. I think that is why the label audit did not fail here

2020-11-16 22:52 UTC, bmuniswamy commented on force-app/main/default/classes/ServiceSessionSelector.cls
> +        Set<String> sessionStatus = new Set<String>{ 'Pending', 'Complete' };
Renamed it to `allowedSessionStatues`

2020-11-16 23:09 UTC, bethbrains approved these changes
Looks good!

2020-11-17 04:33 UTC, lbeller approved these changes

2020-11-17 17:19 UTC, bmuniswamy commented
@lbeller, I have gone ahead and made the changes for the accordion toggle labels that were in a PR that was closed. Can you please look at it and approve the PR.

2020-11-17 17:28 UTC, lbeller approved these changes

2020-11-17 18:01 UTC, merged