Tweaks from Sprint Review
SalesforceFoundation/PMM pull request #383
Opened 2020-12-17 19:35 UTC by jjbennett

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage  
- [ ] CRUD/FLS is enforced in Apex
- [ ] Permission sets are updated to account for CRUD|FLS|Tab|Classes
- [ ] Field sets are updated to account for new fields
- [ ] UX approval or UX not necessary
- [ ] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] PR contains draft release notes
- [ ] QE story level testing completed

2020-12-17 21:07 UTC, jjbennett commented
[W-8595069](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008kg4fIAA/view)

2020-12-17 21:25 UTC, bethbrains commented on force-app/main/default/labels/CustomLabels.labels-meta.xml
> +        <value>This List View has over 2,000 records. Some records may not be shown.</value>
@lbeller  - `list view` or `List View`?

2020-12-17 21:27 UTC, bethbrains approved these changes
One quick Q for @lbeller  but otherwise looks great. You are so thorough, @jjbennett !!

2020-12-17 23:25 UTC, lbeller requested changes
Change requested: change List View to list view

2020-12-17 23:25 UTC, lbeller commented on force-app/main/default/labels/CustomLabels.labels-meta.xml
> +        <value>This List View has over 2,000 records. Some records may not be shown.</value>
list view

2020-12-21 12:58 UTC, jjbennett commented
Thanks for catching that @bethbrains and for the quick feedback @lbeller - the capitalization has been fixed.

2020-12-21 16:27 UTC, lbeller approved these changes

2020-12-21 17:06 UTC, merged