Rollup reports
SalesforceFoundation/PMM pull request #441
Opened 2021-03-09 22:30 UTC by bethbrains

# Critical Changes

# Changes
- New reports:
1. Contacts with 3 Consecutive Absences
2. Contacts Absent for Last Svc Delivery
3. Contacts w/o Recent Service Deliveries

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- ~~Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage~~
- ~~CRUD/FLS is enforced in Apex~~
- ~~Permission sets are updated to account for CRUD|FLS|Tab|Classes~~
- ~~Field sets are updated to account for new fields~~
- [x] UX approval or UX not necessary
- [x] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)
- [ ] All **acceptance criteria** have been met
    - [x] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [x] PR contains draft release notes
- [ ] QE story level testing completed

2021-03-09 22:31 UTC, bethbrains commented
[W-8789464](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000094eYTIAY/view)
[W-8766472](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000094CC3IAM/view)
[W-8766558](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000094CIQIA2/view)

2021-03-10 15:41 UTC, bmuniswamy commented
@bethbrains, I see the same above behavior in the `Contacts with 3 Consecutive Absences` report too. I think it has to do something with the cross filter.

2021-03-10 15:41 UTC, bmuniswamy reviewed
I have a couple of questions.

2021-03-10 17:45 UTC, jjbennett requested changes

2021-03-10 17:45 UTC, jjbennett commented on force-app/main/default/reports/ProgramManagementReports/Contacts_wo_Recent_Service_Deliveries_2SV.report-meta.xml
> +        <language>en_US</language>
I believe we need to remove this flag for orgs that do not have translations enabled.

2021-03-10 22:19 UTC, jjbennett approved these changes

2021-03-11 21:01 UTC, merged

2021-03-11 23:32 UTC, jessicahaas1 reviewed
Looks good