Filter Service Participants that show up on Track Attendance by status, role and stage
SalesforceFoundation/PMM pull request #570
Opened 2022-02-10 22:07 UTC by ptewson-sfdo

This work adds design properties to the attendance tracker component (visible on the service schedule page) to allow admins to filter untracked participants by the Status of Service Participant and Role or Stage of the Program Engagement related to the record. If no filters are specified (what customers will experience at the time this feature is released) than no filtering is applied, meaning that the customer experience should be unchanged until they chose to apply filters. 

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage  
- [ ] CRUD/FLS is enforced in Apex
- [ ] Permission sets are updated to account for CRUD|FLS|Tab|Classes
- [ ] Field sets are updated to account for new fields
- [ ] UX approval or UX not necessary
- [ ] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] PR contains draft release notes
- [ ] QE story level testing completed

2022-02-14 18:31 UTC, dospromptman requested changes
One label in the component properties might need to be updated

2022-02-14 18:32 UTC, dospromptman commented
I think I remember in the discussion of this work item during grooming that we said we wouldn't need to worry about commas existing in picklist values, but I tried adding a picklist value with a comma in both the value and api name and it accepted it.  I'm not sure this logic will support cases where users have added values like that and are trying to filter them using the component properties.

2022-02-15 00:52 UTC, ptewson-sfdo commented on force-app/main/default/lwc/attendance/attendance.js-meta.xml
> +                      label="Excluded Service Participant Statuses"
I believe so - I will confirm that works and then make that update, thanks!

2022-02-15 00:52 UTC, ptewson-sfdo commented on force-app/main/default/lwc/attendance/attendance.js-meta.xml
> +                      description="A comma-delimeted list of API stage values to omit"
Sure should, good catch!

2022-02-15 01:46 UTC, ptewson-sfdo commented on force-app/main/default/lwc/attendance/attendance.js-meta.xml
> +                      label="Excluded Service Participant Statuses"
I'm not sure its possible to use labels for translation here - I definitely want to keep looking into it, but so far as I can tell the label support works when supplying the *value* of the design property, but so far I have yet to find success using custom labels to define the label or description within the meta.xml file. 

For instance, this works to apply the filter:
![image](https://user-images.githubusercontent.com/45107660/153976850-3a933584-6836-4051-9158-1c6ce9e84d3b.png)


But attempting to use labels like so:
```
            <property name="omitProgramEngagementStages"
                      label="{!$Label.Incorrect_Tab}"
                      description="{!$Label.Incorrect_Tab}"
                      default=""
                      type="String" />   
```
Just renders like this:
![image](https://user-images.githubusercontent.com/45107660/153977037-3b40bac3-eb52-4e81-ae24-16bfc8627799.png)

2022-02-15 16:42 UTC, dospromptman approved these changes

2022-02-15 16:56 UTC, merged