Participant Selector Load Performance
SalesforceFoundation/PMM pull request #654
Opened 2022-09-19 15:21 UTC by AndersonTarren

# Critical Changes

# Changes
Improves the performance of load and search within the Participant Selector component.

# Issues Closed

# New Metadata

# Deleted Metadata

# Definition of Done
  Refer to [Asteroids DoD document](https://salesforce.quip.com/iq2mAy4i62oM) to see any additional details for the items below
- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage  
- [ ] CRUD/FLS is enforced in Apex
- [ ] Permission sets are updated to account for CRUD|FLS|Tab|Classes
- [ ] Field sets are updated to account for new fields
- [ ] UX approval or UX not necessary
- [ ] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)
- [ ] All **acceptance criteria** have been met
    - [ ] Developer
    - [ ] Code Reviewer
    - [ ] QA
- [ ] PR contains draft release notes
- [ ] QE story level testing completed

2022-09-20 16:50 UTC, AndersonTarren commented
[W-11550867](https://gus.lightning.force.com/a07EE000013IY5QYAW)

2022-09-21 17:51 UTC, jjbennett reviewed
A couple minor comments but I also notice that when I have more than 3 letters in the search tearm delete until there are only 3 left and then delete again, it deletes all 3 remaining letters. Let me know if you need a video for reference.

2022-09-21 17:51 UTC, jjbennett commented on force-app/main/default/classes/ServiceScheduleCreatorController.cls
> +            cohortIdConvert = (Id) cohortId;
Nitpicky but automatic casting will happen when you call the service method.

2022-09-21 17:51 UTC, jjbennett commented on force-app/main/default/labels/CustomLabels.labels-meta.xml
> +        <value>More than 1000 results found, refine by searching or filtering by Program Cohort</value>
Did we run this past Farzana yet?

2022-09-21 17:51 UTC, jjbennett commented on force-app/main/default/lwc/participantSelector/participantSelector.html
> +                                            theme="warning"
Are we using info over in CaseMan, is warning too strong?

2022-09-21 18:49 UTC, AndersonTarren commented on force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
> +    //Tarren Start
(facepalm)

2022-09-21 18:50 UTC, AndersonTarren commented on force-app/main/default/labels/CustomLabels.labels-meta.xml
> +        <value>More than 1000 results found, refine by searching or filtering by Program Cohort</value>
Yes, she's reviewing the text today.

2022-09-21 19:15 UTC, fanwar-salesforce requested changes
Please change the message to:

This Program has more than 1,000 contacts. Refine the results by filtering by Program Cohort.

2022-09-21 19:18 UTC, AndersonTarren commented
@fanwar-salesforce  - Question on the message.  The proposed change doesn't mention the ability to refine their results by using the text search.  Also, the returned result is Program Engagements, so mentioning 1000 Contacts might be confusing.

2022-09-23 14:35 UTC, jjbennett requested changes
We found an issue with SOSL where only 250 records are being returned. This work item has been implemented as required but we will need to create a new work item to determine how we want to handle the 250 record limit.

2022-09-23 16:10 UTC, fanwar-salesforce requested changes
Here we go for the value: 

Program has more than 1,000 participants. Refine the results by searching or filtering by Program Cohort.

2022-10-03 14:38 UTC, AndersonTarren commented
[W-11550966](https://gus.lightning.force.com/a07EE000013J1eVYAS)
[W-11801818](https://gus.lightning.force.com/a07EE0000175aZOYAY)

2022-10-04 17:58 UTC, jjbennett approved these changes

2022-10-04 18:33 UTC, merged